lantern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings

from . import views



urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='lantern/login.html', extra_context={'title':settings.LANTERN_TITLE, 'login_message': settings.LANTERN_LOGIN_MESSAGE}), name='login'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='lantern/password_reset.html', from_email=settings.EMAIL_FROM, extra_context={'title':settings.LANTERN_TITLE}), name='password_reset'),
    path('password_reset_done', auth_views.PasswordResetView.as_view(template_name='lantern/password_reset_done.html', extra_context={'title':settings.LANTERN_TITLE}), name='password_reset_done'),
    path('password_reset_confirm/<str:uidb64>/<str:token>', auth_views.PasswordResetConfirmView.as_view(template_name='lantern/password_reset_confirm.html', extra_context={'title':settings.LANTERN_TITLE}), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='lantern/password_reset_complete.html', extra_context={'title':settings.LANTERN_TITLE}), name='password_reset_complete'),
    path('password/', auth_views.PasswordChangeView.as_view(template_name='lantern/password_change.html', extra_context={'title':settings.LANTERN_TITLE, 'menu': settings.LANTERN_MENU}), name='password_change'),
    path('password_change_done', auth_views.PasswordChangeDoneView.as_view(template_name='lantern/password_change_done.html', extra_context={'title':settings.LANTERN_TITLE, 'menu': settings.LANTERN_MENU}), name='password_change_done'),
    path('logout', auth_views.LogoutView.as_view(template_name='lantern/logout.html', extra_context={'title':settings.LANTERN_TITLE}), name='logout'),
    path('registration', views.registration, name='registration'),
    path('edit-profile', views.edit_profile, name='edit-profile'),
    path('last-logins', views.last_logins, name='last-logins'),
    path('not-seen', views.not_seen, name='not-seen'),
    path('all-users', views.all_users, name='all-users'),
    path('details/<str:user_id>', views.details, name='details'),
    path('forum/<str:forum>/<int:page>', views.forum, name='forum-page'),
    path('forum/<str:forum>', views.forum, name='forum'),
    path('post/<int:post_id>', views.view_post, name='view-post'),
    path('edit-post/<int:post_id>/<str:origin>', views.edit_post, name='edit-post'),
    path('reply-post/<int:post_id>/<str:origin>', views.reply_post, name='reply-post'),
    path('archive', views.list_archived_forums, name='archive'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lantern.urls')),
]

lantern/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms import ModelForm
from django.db.models import Q
from django.utils import timezone
from csv import DictReader
import html
import datetime


class Forum(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    write_group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, null=True, blank=True)
    is_archived = models.BooleanField(default=False)
    is_writable = models.BooleanField(default=True)
    is_listed = models.BooleanField(default=True)

    def is_user_writable(self, user):
        return self.is_writable and (self.write_group==None or self.write_group in user.groups.all())

    def first_last_post(self):
        posts = self.post_set.all().order_by('date')
        if len(posts)==0:
            return None
        return posts[0].date, posts[len(posts)-1].date  

    def __str__(self):
        return "{} ({})".format(self.name, self.slug)


class NotificationSetting(models.Model):
    ALL = 'ALL'
    IMPORTANT = 'IMPORTANT'
    NONE = 'NONE'
    NOTIFICATIION_CHOICES = [
            (ALL, 'Alle Nachrichten'),
            (IMPORTANT, 'Wichtige Nachrichten'),
            (NONE, 'Keine Nachrichten'),
            ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE, blank=True, null=True)
    value = models.CharField(max_length=20, choices=NOTIFICATIION_CHOICES, default=IMPORTANT)

    def __str__(self):
        return "{} - {}: {}".format(self.user, self.forum, self.value)


def NotificationSettingForm(ModelForm):
    class Meta:
        model = NotificationSetting
        fields = ['value']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthname = models.CharField(max_length=200, blank=True)
    address = models.TextField(blank=True)
    birthdate = models.DateField(null=True, blank=True)
    description = models.TextField(blank=True)
    last_mail_digest = models.DateTimeField(default=timezone.now)
    default_notification = models.CharField(max_length=20, choices=NotificationSetting.NOTIFICATIION_CHOICES, default=NotificationSetting.IMPORTANT)

    def __str__(self):
        return "Profile for {}".format(self.user)


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['birthname', 'address', 'birthdate', 'description']
        labels = {'birthname': 'Geburtsname', 'address': 'Adresse', 'birthdate': 'Geburtstag', 'description': 'Über dich'}


class Contact(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    value = models.CharField(max_length=100)
    name = models.CharField(max_length=100)

    def __str__(self):
        return "{} ({}), {}".format(self.value, self.name, self.profile.user.username)


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'value']
        labels = {'name': 'Art', 'value': 'Wert'}
        help_texts = {'name': 'z.B. Handy, Skype, Signal, Website, LinkedIn, ...'}


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    reply_to = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name='reply_to_set')
    date = models.DateTimeField()
    text = models.TextField()
    important = models.BooleanField(default=False)


    def replies(self):
        res = self.reply_to_set.all().order_by('date')
        return res


    def is_editable(self):
        return (timezone.now() - self.date).total_seconds() < 15 * 60


    def forum_page(self):
        for index, post in enumerate(self.forum.post_set.filter(reply_to__isnull=True).order_by('-date')):
            if self.id == post.id:
                return (index // 10) + 1

    def __str__(self):
        return "{} ({}): {}".format(self.date, self.user, self.text[:100])


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'important']
        labels = {'text': 'Nachricht', 'important': 'Wichtige Nachricht'}
        help_texts = {'important': 'Wichtige Nachrichten werden an alle Nutzer per E-Mail geschickt, die das nicht deaktiviert haben.'}
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)




    

lantern/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.conf import settings
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.utils import timezone
from django.urls import reverse
from itertools import chain

from . import models

def get_context():
    context = {}
    context['title'] = settings.LANTERN_TITLE
    context['menu'] = settings.LANTERN_MENU
    return context


def index(request):
    return redirect(settings.LANTERN_HOME)


def registration(request):
    context = get_context()
    user = models.User()
    profile = models.Profile()
    context['userform'] = models.NewUserForm(instance=user)
    context['profileform'] = models.ProfileForm(instance=profile)
    ContactFormSet = inlineformset_factory(models.Profile, models.Contact, form=models.ContactForm, extra=2)
    context['contactform'] = ContactFormSet(instance=profile, initial=[{'name': 'Telefon', 'value': ''}])
    if request.POST:
        context['userform'] = models.NewUserForm(request.POST, instance=user)
        context['profileform'] = models.ProfileForm(request.POST, instance=profile)
        context['contactform'] = ContactFormSet(request.POST, instance=profile)
        if context['userform'].is_valid() and context['profileform'].is_valid() and context['contactform'].is_valid():
            user = context['userform'].save(commit=False)
            profile = context['profileform'].save(commit=False)
            user.is_active = False
            user.save()
            user.refresh_from_db()
            profile.user = user
            profile.save()
            profile.refresh_from_db()
            for cf in context['contactform']:
                cf.instance.profile = profile
                cf.save()
            messages.success(request, 'Registrierung erfolgreich. Du wirst nach deiner Freischaltung per Mail informiert.')
            send_mail(
                    "{}: Neuer Benuter {}".format(settings.LANTERN_TITLE, user.username),
                    "Ein neuer Benutzer hat sich registriert: {}".format(user.username),
                    settings.EMAIL_FROM,
                    settings.LANTERN_ADMIN_EMAILS)
            return redirect('/login')
    return render(request, 'lantern/registration.html', context)


@login_required
def edit_profile(request):
    context = get_context()
    user = models.User.objects.get(username=request.user.username)
    context['userform'] = models.UserForm(instance=user)
    context['profileform'] = models.ProfileForm(instance=user.profile)
    ContactFormSet = inlineformset_factory(models.Profile, models.Contact, form=models.ContactForm, extra=0)
    context['contactform'] = ContactFormSet(instance=user.profile)
    if request.POST:
        context['userform'] = models.UserForm(request.POST, instance=user)
        context['profileform'] = models.ProfileForm(request.POST, instance=user.profile)
        context['contactform'] = ContactFormSet(request.POST, instance=user.profile)
        if context['userform'].is_valid() and context['profileform'].is_valid() and context['contactform'].is_valid():
            context['userform'].save()
            context['profileform'].save()
            context['contactform'].save()
            messages.success(request, 'Daten wurden aktualisiert.')
            return redirect('edit-profile')

    return render(request, 'lantern/edit-profile.html', context)


@login_required
def last_logins(request):
    context = get_context()
    context['list_name'] = 'Zuletzt gesehen'
    users = models.User.objects.filter(profile__isnull=False, is_active=True).order_by('-last_login')[:20]
    context['users'] = users
    return render(request, 'lantern/list-users.html', context)


@login_required
def not_seen(request):
    context = get_context()
    context['list_name'] = 'Lange nicht gesehen'
    missing = models.User.objects.filter(groups__name='missing')
    nomail = models.User.objects.filter(profile__isnull=False, is_active=True, email__exact="").exclude(groups__name='missing')
    users = models.User.objects.filter(profile__isnull=False, is_active=True).exclude(groups__name='missing').exclude(email__exact='').order_by('last_login')
    context['users'] = chain(missing, nomail, users)
    return render(request, 'lantern/list-users.html', context)


@login_required
def details(request, user_id):
    context = get_context()
    user = get_object_or_404(models.User, pk=user_id) 
    context['show_user'] = user
    return render(request, 'lantern/details.html', context)


@login_required
def all_users(request):
    context = get_context()
    context['list_name'] = 'Alle Benutzer'
    users = models.User.objects.filter(profile__isnull=False, is_active=True).order_by('first_name')
    context['users'] = users
    return render(request, 'lantern/list-users.html', context)


@login_required
def forum(request, forum, page=1):
    context = get_context()
    forum = get_object_or_404(models.Forum, slug=forum)
    context['writable'] = forum.is_user_writable(request.user)
    if context["writable"]:
        post = models.Post()
        post.forum = forum
        if request.POST:
            form = models.PostForm(request.POST, instance=post)
            if form.is_valid():
                post.date = timezone.now()
                post.user = request.user
                post.save()
                return redirect(reverse('forum-page', kwargs={'forum': forum.slug, 'page': page}))
            context['form'] = form
        else:
            context['form'] = models.PostForm()
    posts = forum.post_set.filter(reply_to__isnull=True).order_by("-date") 
    p = Paginator(posts, 10)
    context['forum'] = forum
    context['posts'] = p.page(page).object_list
    left = range(1, min(4, p.num_pages + 1))
    center = range(max(left[-1] + 1, page-3), min(page + 4, p.num_pages + 1))
    if len(center)>0:
        right = range(max(center[-1] + 1, p.num_pages-2), p.num_pages + 1)
    else:
        right = []
    context['pages_left'] = left
    context['pages_center'] = center
    context['pages_right'] = right
    context['sep_left'] = center and center[0] - left[-1] > 1
    context['sep_right'] = center and right and right[0] - center[-1] > 1
    context['current'] = page
    return render(request, 'lantern/forum.html', context)


@login_required
def view_post(request, post_id):
    context = get_context()
    context["post"] = get_object_or_404(models.Post, pk=post_id)
    return render(request, 'lantern/view-post.html', context)


@login_required
def edit_post(request, post_id, origin='forum'):
    context = get_context()
    context["post"] = get_object_or_404(models.Post, pk=post_id)
    context["writable"] = context["post"].forum.is_user_writable(request.user)
    if not context["writable"] or request.user != context['post'].user or not context['post'].is_editable():
        return redirect(reverse('view-post', kwargs={'post_id':post_id}))
    if request.POST:
        context['form'] = models.PostForm(request.POST, instance=context['post'])
        if context['form'].is_valid():
            context['form'].save()
            return redirect(reverse('forum-page', kwargs={'forum': context['post'].forum.slug, 'page': context['post'].forum_page() }))
    else:
        context['form'] = models.PostForm(instance=context['post'])
    return render(request, 'lantern/edit-post.html', context)


@login_required
def reply_post(request, post_id, origin='forum'):
    context = get_context()
    context["post"] = get_object_or_404(models.Post, pk=post_id)
    context["writable"] = context["post"].forum.is_user_writable(request.user)
    if not context["writable"]:
        return redirect(reverse('view-post', kwargs={'post_id':post_id}))
    if request.POST:
        context['form'] = models.PostForm(request.POST)
        if context['form'].is_valid():
            reply = context['form'].save(commit=False)
            reply.date = timezone.now()
            reply.user = request.user
            reply.reply_to = context['post']
            reply.forum = context['post'].forum
            reply.save()
            return redirect(reverse('forum-page', kwargs={'forum': context['post'].forum.slug, 'page': context['post'].forum_page() }))
    else:
        context['form'] = models.PostForm()
        del context['form'].fields['important']
    return render(request, 'lantern/reply-post.html', context)


@login_required
def list_archived_forums(request):
    context = get_context()
    forums = models.Forum.objects.filter(is_listed=True, is_archived=True)
    context['list_name'] = 'Archiv'
    context['forums'] = forums
    return render(request, 'lantern/list-forums.html', context) 

lantern/templates/lantern/details.html
{% extends "lantern/base.html" %}
{% block content %}
<h2>
  {{show_user.first_name}} {{show_user.last_name}}
  {% if show_user.profile.birthname %}
  (geb. {{show_user.profile.birthname}})
  {% endif %}
</h2>
<p>
{{show_user.profile.description}}
</p>
<table class='table'>
  <tr>
    <th>Adresse</th>
    <td>{{show_user.profile.address | linebreaks}}</td>
  </tr>
  <tr>
    <th>Geburtstag</th>
    <td>{{show_user.profile.birthdate}}</td>
  </tr>
  <tr>
    <th>Email</th>
    <td><a href="mailto:{{show_user.email}}">{{show_user.email}}</a></td>
  </tr>
  {% for contact in show_user.profile.contact_set.all %}
  <tr>
    <th>{{contact.name}}</th>
    <td>{{contact.value}}</td>
  </tr>
  {% endfor %}
  <tr>
    <th>Letzter Login</th>
    <td>{{show_user.last_login}}</td>
  </tr>
</table>
{% endblock %}

lantern/templates/lantern/edit-post.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% if form %}
<form method="post">
  {{ form | crispy }}
  {% csrf_token %}
  <input type="submit" name="" id="" value="Abschicken" class='btn btn-primary'>
</form>
{% endif %}
{% endblock %}

lantern/templates/lantern/edit-profile.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='my-4'>Dein Profil</h3>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form action="{% url 'edit-profile' %}" method="post">
{{userform | crispy }}
{{profileform | crispy }}
<h4 class='my-4'>Deine Kontaktinformationen</h4>
{% if contactform.errors %}
    {% for field in contactform %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in contactform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div id="contactform">
{{ contactform | crispy }}
</div>
{% csrf_token %}
<input type="submit" value="Speichern" class='btn btn-primary'>
</form>
<script type="text/javascript">
    $(function() {
        $('#contactform .multiField').formset({
            prefix: '{{ contactform.prefix }}',
            formCssClass: 'clearfix',
            addCssClass: 'add-row btn btn-primary my-3',
            addText: 'Weitere Kontaktinformation hinzufügen',
            deleteCssClass: 'delete-row btn btn-danger mb-3 float-right',
            deleteText: 'Löschen'
        });
    })
</script>
{% endblock %}

lantern/templates/lantern/list-users.html
{% extends "lantern/base.html" %}
{% load lantern_tags %}
{% block content %}
<h2>{{list_name}}</h2>
<p>
<ul class="list-group">
{% for user in users %}
<li class="list-group-item my-1 my-md-2 border-top">
  <a href="{% url 'details' user.id %}" class='mr-3'>
  {{user.first_name}} {{user.last_name}}
  {% if user.profile.birthname %}
  (geb. {{user.profile.birthname}})
  {% endif %}
  </a>
  {% if user|has_group:"missing" %}<span class="badge badge-danger ml-1 float-right">Wird noch gesucht</span>
  {% elif not user.email %}<span class="badge badge-danger ml-1 float-right">Keine E-Mail</span>{% endif %}
  {% not_seen_for_days user 1100 as not_seen %}
  {% if not_seen %}<span class="badge badge-secondary ml-1 float-right">Lange nicht gesehen</span>{% endif %}
  <br>
  {% if user.last_login %}
    Letzter Login: {{user.last_login }} Uhr
    
  {% endif %}
</li>
  
{% endfor %}
</ul>
</p>
{% endblock %}

lantern/templates/lantern/login.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if form.errors %}
<p>Benutername und Passwort stimmen nicht überein.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Du hast keine Berechtigung, diese Seite anzuzeigen.</p>
    {% else %}
    <p>Bitte logge dich ein, um diese Seite zu sehen.</p>
    {% endif %}
{% endif %}

<h2 class='mb-4'>Login</h2>

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
{{ form | crispy }}

<input type="submit" value="Einloggen" class='btn btn-primary'>
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p class='my-4'><a href="{% url 'password_reset' %}">Benutzername und/oder Passwort vergessen</a></p>
<p class='my-4'>{{ login_message }}</p>

{% endblock %}

lantern/templates/lantern/logout.html
{% extends "lantern/base.html" %}
{% block content %}
  Ciao.
{% endblock %}

lantern/templates/lantern/password_change.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Passwort ändern</h2>

<form method="post">{% csrf_token %}

{{ form | crispy }}

<input type="submit" value="Passwort ändern" class="btn btn-primary">

</form>

{% endblock %}

lantern/templates/lantern/password_change_done.html
{% extends "lantern/base.html" %}

{% block content %}
<h2>Passwort ändern</h2>
<p>Dein Passwort wurde geändert.</p>
{% endblock %}

lantern/templates/lantern/password_reset.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<p>Trage hier Deine Email-Adresse ein, die Du benutzt hast und du bekommst deinen Username zugesendet, sowie einen Link, um das Passwort neu zu setzen.</p>

<form action="{% url 'password_reset' %}" method="post">
  {% csrf_token %}
 {{form | crispy }}
 <input type="submit" value="Abschicken">
 </form>
{% endblock %}

lantern/templates/lantern/password_reset_complete.html
{% extends "lantern/base.html" %}
{% block content %}
 Dein Passwort wurde geändert. 
{% endblock %}

lantern/templates/lantern/password_reset_confirm.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if validlink %}
  
<form method="post">
{{form | crispy }}
{% csrf_token %}
<input type="submit" value="Passwort neu setzen.">

</form>
{% else %}
  Link ungültig.
{% endif %}

{% endblock %}

lantern/templates/lantern/password_reset_done.html
{% extends "lantern/base.html" %}
{% block content %}
  Du hast Post.
{% endblock %}

lantern/templates/lantern/registration.html
{% extends "lantern/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'registration' %}" method="post">
{{userform | crispy }}
{{profileform | crispy }}
<h4 class='my-4'>Deine Kontaktinformationen</h4>
{% if contactform.errors %}
    {% for field in contactform %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in contactform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div id="contactform">
{{ contactform | crispy }}
</div>
{{ contactform.management_form }}
{% csrf_token %}
<input type="submit" value="Registrierung absenden" class='btn btn-primary'>
</form>
<script type="text/javascript">
    $(function() {
        $('#contactform .multiField').formset({
            prefix: '{{ contactform.prefix }}',
            formCssClass: 'clearfix',
            addCssClass: 'add-row btn btn-primary my-3 d-none',
            addText: 'Weitere Kontaktinformation hinzufügen',
            deleteCssClass: 'delete-row btn btn-danger mb-3 float-right d-none',
            deleteText: 'Löschen'
        });
    })
</script>
{% endblock %}

lantern/templates/lantern/reply-post.html
{% extends "lantern/base.html" %}
{% load lantern_tags %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="card my-md-3 my-sm-2">
  <div class="card-body">
    <h5 class="card-title">
      <span class="align-middle">
        {{post.user.first_name}} {{post.user.last_name}}
        {% if post.important %}<span class="badge badge-warning ml-3 float-right">Wichtig</span>{% endif %}
      </span>
    </h5>
    <h6 class="card-subtitle mb-2 text-muted">{{post.date}}</h6>
    <p class="card-text">{{post.text | linebreaksbr}}</p>
    {% for reply in post.replies %}
    <p class="comment border-top ml-2 my-2 p-1">{{reply.text}} – <a href="{% url 'details' reply.user.id %}">{{reply.user.first_name}} {{reply.user.last_name}}</a>
    <span class='comment-date'>{{reply.date}}</span></p>
    {% endfor %}
  </div>
</div>
<h4>Deine Antwort</h4>
{% if form %}
<form method="post">
  {{ form | crispy }}
  {% csrf_token %}
  <input type="submit" name="" id="" value="Abschicken" class='btn btn-primary'>
  <a class='btn btn-secondary' href="{% url 'forum-page' post.forum.slug post.forum_page %}">Zurück</a>
</form>
{% endif %}
{% endblock %}